### ISSUE TITLE
Incorrect rule parse causing a ton of FPs

### ISSUE THREAD

**Issue by markuskont** [markuskont/go-sigma-rule-engine#25]
Following rule is not parsed correctly. It becomes a `keyword` rule, rather than `selection`. Correct behavior would be to fail while parsing this rule, as selection object works on key-value lookup. Which we clearly cannot do here.

```
detection:
  condition: all of selection
  selection:
  - Set-OabVirtualDirectory
  - ExternalUrl
  - Page_Load
  - script
```

FPs are caused since `all of` is basically ignored as keywords are considered a `OR` match. Maybe that behavior should be improved as well.
